### ISSUE TITLE
Code Review - Isaac (mainly) and Nas

### ISSUE THREAD

**Issue by nascho** [fac30/ali-andrei-agency#16]
1. When screen is smaller difficult to read text on screen
2. Logo alignment on smaller screen is off on Y/Cross axis, over laps hero banner
3. Burger menu model is too large and takes up the entire screen and the text is difficult to read.
4. Contact form too small for the area provided, looks out of place.

Everything else was very well executed, I like the colour combinations and the feel of the site.
We liked the arrow at the bottom of the page to scroll back up (would have been nice if it followed while scrolling the page).

**Comment by revforev** [comment]
thanks Isaac and Nas
